# -*- coding: utf-8 -*-
"""Programmers_Level 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nzBf7jRBu2poVlxEqIxQ14ZNsjJvKfid

Description : 
정수 num이 짝수일 경우 "Even"을 반환하고 홀수인 경우 "Odd"를 반환하는 함수, solution을 완성해주세요.

제한 조건 : 
num은 int 범위의 정수입니다.
0은 짝수입니다.
"""

def solution(num):
    if num % 2:
        return "Odd"
    else:
        return "Even"

"""Description : 
정수 n을 입력받아 n의 약수를 모두 더한 값을 리턴하는 함수, solution을 완성해주세요.

제한 사항 : 
n은 0 이상 3000이하인 정수입니다.
"""

def solution(n):
    return sum([i for i in range(1, n+1) if (n % i) == 0])